# Introduction to Numpy

# small example

In [2]:
"""
-----------------------------------------------------
| Region | Temperature | Rainfall(mm) | Humidity(%) |
-----------------------------------------------------
| Kanto  |     73      |      67      |    43       |
-----------------------------------------------------
| Johto  |     91      |      88      |    64       |
-----------------------------------------------------
| Hoenn  |     87      |      134     |    58       |
-----------------------------------------------------
| Sinnoh |     102     |      43      |    37       |
-----------------------------------------------------
| Unova  |     69      |      96      |    70       |
-----------------------------------------------------
"""
# converting to set
# to find yield of apples above areas
# formula is : temp * w1 + rainfall * w2 + humidity * w3
# w1 = 0.3  w2 = 0.2  w3 = 0.5

'\n-----------------------------------------------------\n| Region | Temperature | Rainfall(mm) | Humidity(%) |\n-----------------------------------------------------\n| Kanto  |     73      |      67      |    43       |\n-----------------------------------------------------\n| Johto  |     91      |      88      |    64       |\n-----------------------------------------------------\n| Hoenn  |     87      |      134     |    58       |\n-----------------------------------------------------\n| Sinnoh |     102     |      43      |    37       |\n-----------------------------------------------------\n| Unova  |     69      |      96      |    70       |\n-----------------------------------------------------\n'

In [1]:
Kanto = [73, 67, 43]
Johto = [91, 88, 64]
Hoenn = [87, 134, 58]
Sinnoh = [102, 43, 37]
Unova = [69, 96, 70]
w1 = 0.3  
w2 = 0.2  
w3 = 0.5
weights = [w1, w2, w3]

In [2]:
weights

[0.3, 0.2, 0.5]

In [3]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [4]:
crop_yield(Kanto, weights)

56.8

# using numpy for this example

In [5]:
import numpy as np
kanto = np.array([73, 67, 43])
weights = np.array([w1, w2, w3])

In [6]:
kanto

array([73, 67, 43])

In [7]:
weights

array([0.3, 0.2, 0.5])

In [8]:
type(kanto)
type(weights)

numpy.ndarray

In [9]:
np.dot(kanto, weights)

56.8

In [22]:
# full code 
import numpy as np
kanto = np.array([73, 67, 43])
johto = np.array([91, 88, 64])
hoenn = np.array([87, 134, 58])
sinnoh = np.array([102, 43, 37])
unova = np.array([69, 96, 70])
weights = np.array([w1, w2, w3])
np.dot(kanto, weights)           # one meyhod

56.8

In [11]:
# before code
Kanto = [73, 67, 43]
w1 = 0.3  
w2 = 0.2  
w3 = 0.5
weights = [w1, w2, w3]
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result
crop_yield(Kanto, weights)

56.8

In [12]:
(kanto * weights).sum()      # second method

56.8

# Time difference 

In [13]:
import numpy as np
# python list
bg = list(range(1000000))             # 1 to 1000000-1
rt = list(range(1000000, 2000000))    # 1000000 to 2000000-1
# Numpy array
bg_np = np.array(bg, dtype=np.int64)
rt_np = np.array(rt, dtype=np.int64)

In [14]:
%%time
result = 0
for x1, x2 in zip(bg, rt):
    result += x1*x2
print(result)

833332333333500000
CPU times: total: 250 ms
Wall time: 373 ms


In [15]:
%%time
u = np.dot(bg_np, rt_np)
print(u)

833332333333500000
CPU times: total: 0 ns
Wall time: 2.99 ms


# two dimension array

In [16]:
climate_d = [[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70]]
climate_d

[[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]]

In [17]:
climate_np = np.array(climate_d, dtype=np.int64)
climate_np.shape

(5, 3)

In [18]:
weights

[0.3, 0.2, 0.5]

In [23]:
weights.shape

(3,)

In [24]:
weights.dtype

dtype('float64')

In [25]:
climate_np.dtype

dtype('int64')

In [26]:
np.matmul(climate_np, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [27]:
%%time
si = climate_np @ weights
si

CPU times: total: 0 ns
Wall time: 0 ns


array([56.8, 76.9, 81.9, 57.7, 74.9])

# Final code of 2D

In [29]:
climate_d = [[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70]]
climate_np = np.array(climate_d, dtype=np.int64)
d = np.matmul(climate_np, weights)
sv = climate_np @ weights
print(d)
sv

[56.8 76.9 81.9 57.7 74.9]


array([56.8, 76.9, 81.9, 57.7, 74.9])

# Saving the data in jovian website

In [2]:
pip install jovian --upgrade --quiet 

Note: you may need to restart the kernel to use updated packages.


In [1]:
import jovian

In [2]:
jovian.commit(project='Numpy')

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.com/ ):
API KEY: ········
[jovian] Creating a new project "sivaalgebra27/Numpy"
[jovian] Committed successfully! https://jovian.com/sivaalgebra27/numpy


'https://jovian.com/sivaalgebra27/numpy'

# Using CSV file 

# importing file 

In [3]:

import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x198b80687d0>)

# converting to arrays

In [6]:
import numpy as np

# Read the data from the file 'climate.txt'
climate_np = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [7]:
climate_np

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [8]:
climate_np.shape

(10000, 3)

In [11]:
weights = np.array([0.3, 0.2, 0.5])
weights.dtype

dtype('float64')

# finding yeilds of apples

In [12]:
yeilds = climate_np @ weights

In [13]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [14]:
yeilds.shape

(10000,)

In [15]:
 fin = np.concatenate((climate_np, yeilds.reshape(10000, 1)), axis=1)   

In [16]:
fin

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

# saving in same file

In [17]:
np.savetxt('climate.txt',
            fin,
            fmt= '%.2f',
            header='temperature,rainfall,humidity,yeild_apples',
            comments='')


In [18]:
jovian.commit(project='Numpy')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sivaalgebra27/numpy" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/sivaalgebra27/numpy


'https://jovian.com/sivaalgebra27/numpy'

# Matrix Operations

In [30]:
import numpy as np
rt = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
ty = np.array([[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]])

# Arthmatic operation

In [31]:
# addtion numbers
rt + ty

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [32]:
# add of scalar
rt + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
# subtraction numbers
rt - ty

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [34]:
#subtraction of sclar
rt - 3

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [35]:
# division of sclar
ty / 2

array([[ 6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. ]])

In [37]:
# multiply numbers
rt * ty

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [38]:
# Modulus with sclar
rt % 3

array([[1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]], dtype=int32)

#  Numpy arrays support brodcasting, which is used to arthmatic operations with two different arrays 

In [39]:
yu = np.array([4, 5, 6, 7])

In [40]:
rt.shape

(3, 4)

In [41]:
yu.shape

(4,)

In [42]:
rt + yu

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19]])

In [74]:
import jovian
jovian.commit(project='Numpy')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sivaalgebra27/numpy" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/sivaalgebra27/numpy


'https://jovian.com/sivaalgebra27/numpy'

# logicall operation

In [43]:
import numpy as np
rt = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
ty = np.array([[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]])

In [44]:
rt == ty

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [46]:
rt != ty

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [47]:
rt >= ty

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [48]:
rt <= ty

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [49]:
rt < ty

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
rt > ty

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [51]:
(rt == ty).sum()

0

# Array indexing and slicing

In [52]:
yu = np.array([
    [[11, 12, 13, 14],
     [15, 16, 17, 18]],
    [[15, 16, 17, 18],
     [19, 20, 21, 22]],
    [[19, 20, 21, 22],
     [23, 24, 25, 26]]])
yu.shape

(3, 2, 4)

In [53]:
yu[2, 1, 3]            # taking single array

26

In [54]:
# mixing indices and ranges
yu[1:, 0:1, :2]

array([[[15, 16]],

       [[19, 20]]])

In [55]:
yu[1:, 0:1, :2].shape

(2, 1, 2)

In [56]:
# User fewer indices
yu[1]

array([[15, 16, 17, 18],
       [19, 20, 21, 22]])

In [57]:
yu[:2, 1]

array([[15, 16, 17, 18],
       [19, 20, 21, 22]])

In [58]:
import jovian
jovian.commit(project='Numpy')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[jovian] Error: Failed to read the Jupyter notebook. Please re-run this cell to try again. If the issue persists, provide the "filename" argument to "jovian.commit" e.g. "jovian.commit(filename='my-notebook.ipynb')"


## You can covert numpy array to python list

In [59]:
import numpy as np

# Creating a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])

# Converting the NumPy array to a Python list
python_list = numpy_array.tolist()

# Displaying the Python list
print(python_list)

[1, 2, 3, 4, 5]


In [60]:
type(python_list)

list

## Other ways of creating Numpy arrays

In [3]:
# null array
ui = np.zeros((3,3))
ui

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
climate_d = [[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70]]
weights_d = [[0.3, 0.2, 0.5], [0.1, 0.4, 0.6], [0.7, 0.8, 0.9]]
weights = np.array(weights_d, dtype=np.float64)
climate_np = np.array(climate_d, dtype=np.float64)
d = np.matmul(climate_np, weights)
sv = climate_np @ weights
print(d)
print(sv)                                                                                        

[[ 58.7  75.8 115.4]
 [ 80.9 104.6 155.9]
 [ 80.1 117.4 176.1]
 [ 60.8  67.2 110.1]
 [ 79.3 108.2 155.1]]
[[ 58.7  75.8 115.4]
 [ 80.9 104.6 155.9]
 [ 80.1 117.4 176.1]
 [ 60.8  67.2 110.1]
 [ 79.3 108.2 155.1]]


In [62]:
# all are one
io = np.ones([2, 2,3])
io

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [63]:
# Identity Matrix 
op = np.eye(3)
op

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
# random vector
pa = np.random.rand(6)
pa

array([0.23978921, 0.38884246, 0.0465164 , 0.06500069, 0.29490803,
       0.75988373])

In [65]:
# random matrix 
sd = np.random.randn(3, 4)
sd

array([[ 0.03056276, -1.15217047, -1.31073452, -0.27491441],
       [-0.28312016, -0.37953496, -0.73501247, -1.06815822],
       [-0.71966108,  1.66711763, -0.0468606 ,  0.71296123]])

In [66]:
# Fixed value
df = np.full([3, 3], 42)
df

array([[42, 42, 42],
       [42, 42, 42],
       [42, 42, 42]])

In [67]:
# range with Start and Stop
fg = np.arange(10, 90, 3)
fg

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [68]:
# we reshape array also
fg.reshape(9,3)

array([[10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43],
       [46, 49, 52],
       [55, 58, 61],
       [64, 67, 70],
       [73, 76, 79],
       [82, 85, 88]])

In [69]:
# equally Space numbers in range 
gh = np.linspace(3, 30, 10)
gh

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [46]:
import jovian
jovian.commit(project='Numpy')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sivaalgebra27/numpy" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/sivaalgebra27/numpy


'https://jovian.com/sivaalgebra27/numpy'

## We've covered the following topics :
###     • Going from Python lists to Numpy arrays
###     • Operating on Numpy arrays
###     • Benefits of using Numpy arrays over lists
###     • Multi-dimensional Numpy arrays
###     • Working with CSV data files
###     • Arithmetic operations and broadcasting
###     • Array indexing and slicing
###     • Other ways of creating Numpy arrays


## Check out the following resouces for learning more about Numpy:
###   • Official tutorial: https://numpy.org/devdocs/user/quickstart.html
###   • Numpy tutorial on W3Schools: https://www.w3schools.com/python/numpy_intro.asp
###   • Advanced Numpy (exploring the internals):  
### http://scipy- lectures.org/advanced/advanced_numpy/index.html

# concatenate():

## Syntax : numpy.concatenate((arr1, arr2, …), axis=0, out=None)

### Parameters :
#### arr1, arr2, … : [sequence of array_like] The arrays must have the same shape, except in the dimension corresponding to axis.
#### axis : [int, optional] The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.
#### out : [ndarray, optional] If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.
#### Return : [ndarray] The concatenated array.

In [70]:
array_1 = [[1, 2], [3, 4]]
array_2 = [[5, 6], [7, 8]]
array_con = np.concatenate((array_1, array_2), axis = 0)
array_con

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [71]:
array_con1 = np.concatenate((array_1, array_2), axis = 1)
array_con1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [72]:
array_con2 = np.concatenate((array_1, array_2), axis = None)
array_con2

array([1, 2, 3, 4, 5, 6, 7, 8])

# 100 Numpy Exercise 

## Source: https://github.com/rougier/numpy-100

# Interacting with the OS and file system

In [73]:
import os

In [74]:
os.getcwd()       # To file location of this file

'C:\\Users\\sivaa\\NumPy and  Pandas'

In [75]:
help(os.listdir)    # to get the list of files in a directory 

Help on built-in function listdir in module nt:

listdir(path=None)
    Return a list containing the names of the files in the directory.

    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.

    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.



In [76]:
os.listdir('.')          # relative path

['.ipynb_checkpoints', '.jovianrc', 'climate.txt', 'data', 'Numpy.ipynb']

In [77]:
os.listdir('/usr')       # absolute path

FileNotFoundError: [WinError 3] The system cannot find the path specified: '/usr'

In [78]:
os.makedirs('./data1', exist_ok = True) # to create new file directory

In [79]:
'data' in os.listdir('.')

True

In [80]:
os.listdir('./data')

[]

# Adding New files in the dirctory

In [81]:
url1 = 'https://docs.google.com/presentation/d/1HrHWvxAu2pSOeAQSN5xJ8vvU1fokRPR-/edit?usp=drive_link&ouid=101341994574571611875&rtpof=true&sd=true'

In [82]:
import urllib.request

In [83]:
urllib.request.urlretrieve(url1, './data')

PermissionError: [Errno 13] Permission denied: './data'